spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springCloud?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: root
lagouwork:
  limit:
    time-lenth: 2 
    visit-times: 5
